### ISSUE TITLE
`libertinehologopatch.sty' not found

### ISSUE THREAD

**Issue by wpfnlp** [texno3/easybook#2]
LaTeX Error: File `libertinehologopatch.sty' not found.

**Comment by texno3** [comment]
我对cnltx-doc文档类进行了一些包括字体在内的改动，放在了[cnltx-doc](https://github.com/texno3/easybook/tree/cnltx-doc)分支中。

**Comment by texno3** [comment]
> LaTeX Error: File `libertinehologopatch.sty' not found.



> LaTeX Error: File `libertinehologopatch.sty' not found.

我对cnltx-doc文档类进行了一些包括字体在内的改动，放在了[cnltx-doc](https://github.com/texno3/easybook/tree/cnltx-doc)分支中。
